services:
  zabbix-java-gateway:
    image: "${IMAGES_REGISTRY}/${ZABBIX_JAVA_GATEWAY_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}"
    container_name: zabbix-java-gateway
    restart: "${RESTART_POLICY}"
    networks:
      zabbix-net:
        ipv4_address: ${ZABBIX_GATEWAY}

include:
  - zabbix-server-mysql.yaml
  - zabbix-mysql.yaml
  - zabbix-agent.yaml
  - zabbix-web-nginx-mysql.yaml
  # - zabbix-grafana.yaml


volumes:
  zabbix-mysql:
  zabbix-server:
  # zabbix-grafana:

networks:
  zabbix-net:
    driver: bridge
    ipam:
     config:
       - subnet: ${SUBNET}
         gateway: ${GATEWAY}