version: "3"
services:
  wyl:
    image: registry.cn-chengdu.aliyuncs.com/shulinjing/watchyourlan
    network_mode: "host"
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Asia/Shanghai                  # 必选：填写正确的时区
      IFACES: "enp3s0"                   # 必选：1个或多个接口
      HOST: "0.0.0.0"                    # 可选：默认值：0.0.0.0
      PORT: "8840"                       # 可选：默认值：8840
      TIMEOUT: "120"                     # 可选：时间（秒），默认值：120
      #SHOUTRRR_URL: ""                  # 可选：设置要通知的url
      #THEME: "sand"                     # 可选
      #COLOR: "dark"                     # 可选

# 警告！WYL 需要“主机”网络模式才能工作。因此，在此设置中，WYL 端口将被暴露。您需要使用防火墙或其他措施限制对它的访问

  forauth:
    image: registry.cn-chengdu.aliyuncs.com/shulinjing/forauth
    restart: unless-stopped
    ports:
    - 8800:8800 # Proxy port
    - 8801:8801 # Config port
    volumes:
    - ~/.dockerdata/forauth:/data/ForAuth
    environment:
      TZ: Asia/Shanghai                    # 必选：填写正确的时区
      FA_TARGET: "192.168.32.158:8840"     # 可选：wyl 主机的 IP：端口
      FA_AUTH: "true"                      # 可选：true-启用，默认值：false
      FA_AUTH_EXPIRE: 7d                   # 可选：过期时间，默认值：7d
      FA_AUTH_PASSWORD: "123456Aa"
      # 警告！如果密码设置为环境变量，则每个“$”字符都必须用另一个“$”转义，如“$$”
      # 可选：使用bcrypt加密密码，操作方法：https://github.com/aceberg/ForAuth/blob/main/docs/BCRYPT.md（在本例中，FA_AUTH_PASSWORD=pw）
      FA_AUTH_USER: admin            # 可选：用户名
