version: "3"
services:
  chandao:
    container_name: "chandao"
    image: easysoft/zentao:latest
    ports:
      - "9999:80"
      - "3226:3306"
    volumes:
      - /home/chandao/zentaopms:/www/zentaopms 
      - /home/chandao/mysqldata:/var/lib/mysql
    networks: 
      chandao_net:
        ipv4_address: 10.10.10.10
    mac_address: 02:42:ac:11:00:00
    restart: on-failure
    environment:
       MYSQL_ROOT_PASSWORD: 123456Aa
networks:
  chandao_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24