services:
  zabbix-mysql:
    image: "${IMAGES_REGISTRY}/${MYSQL_IMAGE}:${MYSQL_IMAGE_TAG}"
    container_name: zabbix-mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: "${RESTART_POLICY}"
    volumes:
      - zabbix-mysql:/var/lib/mysql:rw 
    networks:
      zabbix-net:
        ipv4_address: ${MYSQL_ADDRESS}