version: '3.9'
services:
  portainer-ce:
    container_name: portainer
    image: 'portainer/portainer-ce:2.21.0'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    ports:
      - '9443:9443'
      - '8000:8000'
