# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 192.168.32.146:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  # - "/etc/prometheus/rules/alerts.yml"
    - "/etc/prometheus/rules/*.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: "prometheus"

    metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # static_configs:
    #   - targets: ["192.168.32.146:9100"]
    #   - targets: ["192.168.33.205:9182"]
    #   - targets: ["192.168.33.199:9100"]
    #   - targets: ["192.168.32.146:9090"]
    #   - targets: ["192.168.32.146:32768"]
    #   - targets: ["121.41.114.211:9100"]
    #   - targets: ["34.239.0.205:9100"]
    #   - targets: ["192.168.1.221:9100"]
    #   - targets: ["10.1.20.201:9100"]
    #   - targets: ["10.1.20.247:9100"]

#  - job_name: "mysqld_exporter"
#    static_configs:
#      - targets: ["192.168.32.146:33060"]

  - job_name: 'linux'
    file_sd_configs:
    - files:
      - 'sd_config/linux.yml'
      refresh_interval: 30m  # 每隔30分钟检查一次

  - job_name: 'windows'
    file_sd_configs:
    - files:
      - 'sd_config/windows.yml'
      refresh_interval: 30m  

  - job_name: 'snmp'
    file_sd_configs:
    - files:
      - 'sd_config/snmp.yml'
      refresh_interval: 30m  
    metrics_path: /snmp
    params:
      module: [HUAWEI]  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.32.146:9116  
